repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2" # pick a git hash / tag to point to
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
